name: Build Homely dashboard PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: |
          yarn install

      - name: Compile app
        run: |
          yarn build

      - name: Run unit tests
        run: |
          yarn test --watchAll=false
